### ISSUE TITLE
Refactor chat_client.js into a React component

### ISSUE THREAD

**Issue by caffeine-based-lifeform** [SynapseNetwork/Synapse-Desktop#29]
Refactor the class of chat_client.js into a React component that wraps the chat client functionality, using nested routes for rendering children components (Contacts, chat/conversation).

**Comment by JJ** [comment]
Is it worth the while? At this stage? What do you want to achieve?

**Comment by caffeine-based-lifeform** [comment]
I think it will make the implementation of the signal protocol much easier. Regarding the coding time, 
 it should not take more than a couple of hours. 
Once I got a better perspective of how to use the stack it became clear that having a separate class for handling the socket events was unnecessary and was adding extra complexity.
